---
abstract: 'IO Interface to compressed data files/buffers'
author:
  - 'Paul Marquess <pmqs@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Compress
no_index:
  directory:
    - t
    - inc
    - t
    - private
requires:
  Compress::Raw::Bzip2: '2.070'
  Compress::Raw::Zlib: '2.070'
  Scalar::Util: '0'
version: '2.070'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
